#!/bin/sh

gnuplot -persist << EOF
set term postscript enhanced color "Times-Roman" 25
set autoscale
set key right top
set pointsize 1.3
set xlabel "Jbb"
set ylabel "Jab"
set yrange [0.5:2.5]
set mxtics 2
set mytics 2
set output "phase-diagram.eps"
plot "a.txt" u 1:2 notitle w p lt -1 pt 7,\
"a.txt" u 1:3 notitle w p lt 3 pt 65,\
"a.txt" u 1:4 notitle w p lt 1 pt 13,\
0.512667*x+0.740222 lt -1,\
0.598*x+0.109556 lt -1

EOF

#f(x)=0.512667*x+0.740222 w l 1
