#!/bin/sh

gnuplot -persist << EOF
set term postscript enhanced color "Times-Roman" 28
set autoscale
set key right top
set xlabel "Jab"
set ylabel "Pab"
set output "Pab-compare-new3.eps"
plot "Paa1.dat" u 3:6 t "T=0.5" w p ps 1.2 lt -1 pt 7,\
"Paa4.dat" u 3:6 t "T=1.0" w p ps 1.2 lt 3 pt 65,\
"Paa3.dat" u 3:6 t "T=2.0" w p ps 1.3 lt 4 pt 11,\
"Paa2.dat" u 3:6 t "T=3.0" w p ps 1.2 lt 1 pt 13
EOF
#set pointsize 1.2
